# Generated by Django 3.0.2 on 2021-12-26 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20211226_0139'),
        ('reviews', '0002_auto_20211226_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.Movie'),
        ),
    ]
